In [2]:
# Dictionaries in Python have keys and values:
    # person = {"...": "..."}
# where person is a row case, '{"...": ' is our key (column), and ' "..."}' is our (column) value
# "keys are the columns and the values are the rows"
# pandas: two-dimentional data structure
person = { # row case (a single person)
    "first": "Corey", # column (key) 'first' with 'Corey' column data
    "last": "Shafer",
    "email": "CoreyMShafer@gmail.com"
}

In [3]:
people = { # row cases (people --> 1)
    "first": ["Corey"], # instead of having a single value here, we now use a list [...] that allows us to contain multipe values
    "last": ["Shafer"],
    "email": ["CoreyMShafer@gmail.com"]
}

In [4]:
people = { # row cases (people --> 3)
    "first": ["Corey", 'Jane', 'John'], # Corey --> person 1, Jane --> person 2, John --> person 3
    "last": ["Shafer", 'Doe', 'Doe'],
    "email": ["CoreyMShafer@gmail.com", 'JaneDoe@gmail.com', 'JohnDoe@gmail.com']
}

In [5]:
people['email'] # shows all the email column values (case['...'])

['CoreyMShafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com']

In [6]:
# We can create a dataframe from this dictionary and see how it looks like
import pandas as pd

In [7]:
df = pd.DataFrame(people) # assigning a df variable to a module object pd referenced to the method .DataFrame(...) with a passed dictionary argument, so that creating a table of rows of columns
df # calling df (print) --> here our array is two-dimentional since it has rows and columns

# 0, 1, 2 --> indexes --> "unique" values for a row

   first    last                   email
0  Corey  Shafer  CoreyMShafer@gmail.com
1   Jane     Doe       JaneDoe@gmail.com
2   John     Doe       JohnDoe@gmail.com

In [8]:
# how to access information within the dataframe:

# 1st). Let's just access the values of a single column
df['email'] # access the email column values from the dataframe var df (display)
# bracket notation

# the code above returns a series, we can see it by checking its type (check next line of code)

0    CoreyMShafer@gmail.com
1         JaneDoe@gmail.com
2         JohnDoe@gmail.com
Name: email, dtype: str

In [9]:
df[['email']]

                    email
0  CoreyMShafer@gmail.com
1       JaneDoe@gmail.com
2       JohnDoe@gmail.com

In [10]:
type(df['email']) # pandas.Series --> series oject --> email column
# Series: 
        # It is also defined as a one-dimentional array: (rows of data from a single column)
        # dataframe: A container for multiple of these Series objects.

        # So we can think of our dataframe as a two-dimentional container (rows and columns), which represents a collection of one-dimentional arrays named series objects (rows of data from a single column)
        # therefore, since our df has three columns, then it contains three column-based Series objects (Column A (Series 1), Column B (Series 2), Column C (Series 3)), which are bueprints of our dataframe which contain specific data according to their index (the Series also has an index as well) 

        # In Pandas, the primary blueprint of a DataFrame is a collection of columns (vertical arrays) aligned by a common index (the rows)

pandas.Series

In [11]:
df.email # df['email'] --> returns the same Series object of the email value(s)
# dot notation
# it is preferable to use the bracket notation since the name of columns and method referals might produce some type of errors when matching

0    CoreyMShafer@gmail.com
1         JaneDoe@gmail.com
2         JohnDoe@gmail.com
Name: email, dtype: str

In [12]:
# How to access multiple columns: we can use the bracket notation and pass in a list of the columns that we want

# access both last name and email columns
df[['last', 'email']] # passing a list inside of the brackets 
# Series: Single column of rows
# Here, we do not have a Series but rather a filtered-down dataframe with specified columns 'last' and 'email'

     last                   email
0  Shafer  CoreyMShafer@gmail.com
1     Doe       JaneDoe@gmail.com
2     Doe       JohnDoe@gmail.com

In [13]:
# If you have a lot of columns (names), I want to see all of them easily, then then we can grab the columns specifically by saying:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [14]:
# In order to see a row, we can use the loc and iloc indexes:
# --> iloc # allows us to access rows by integer location (iloc --> integer location)

# To get the first row, we can say:
df.iloc[0] # it returns a group of Series that contain the values of that first row (index 0) of data

# Whenever we are accessing a row it's gonna set that index to the column name so that we know what those values are

first                     Corey
last                     Shafer
email    CoreyMShafer@gmail.com
Name: 0, dtype: str

In [15]:
# Just like when we selected multiple columns we can select multiple rows as well by passing in a list of integers:
df.iloc[[0, 1]] # getting the first and second row (passing in an inner list)

   first    last                   email
0  Corey  Shafer  CoreyMShafer@gmail.com
1   Jane     Doe       JaneDoe@gmail.com

In [26]:
# With this iloc and loc indexeds we can select columns as well:
# rows --> firts argument, columns --> second argument
df.iloc[[0, 1], 2] # gets the email addresses of the first two rows
# '[0, 1],' --> gets first and second row, '2]' --> gets the third column

0    CoreyMShafer@gmail.com
1         JaneDoe@gmail.com
Name: email, dtype: str

In [27]:
df.iloc[[0, 1], [1, 2]]

     last                   email
0  Shafer  CoreyMShafer@gmail.com
1     Doe       JaneDoe@gmail.com

In [17]:
# iloc --> searching by integer location 
# loc --> searchin gby label (labels for rows --> indexes (default range of integers))
df

   first    last                   email
0  Corey  Shafer  CoreyMShafer@gmail.com
1   Jane     Doe       JaneDoe@gmail.com
2   John     Doe       JohnDoe@gmail.com

In [18]:
df.iloc[[0]]

   first    last                   email
0  Corey  Shafer  CoreyMShafer@gmail.com

In [19]:
df.iloc[0]

first                     Corey
last                     Shafer
email    CoreyMShafer@gmail.com
Name: 0, dtype: str

In [20]:
df.loc[0]

first                     Corey
last                     Shafer
email    CoreyMShafer@gmail.com
Name: 0, dtype: str

In [21]:
df.loc[[0]]

   first    last                   email
0  Corey  Shafer  CoreyMShafer@gmail.com

In [22]:
df.loc[[0, 1]]

   first    last                   email
0  Corey  Shafer  CoreyMShafer@gmail.com
1   Jane     Doe       JaneDoe@gmail.com

In [23]:
# since we are using loc, we do not need an index to select our columns (second argument inside []) but rather labels 
df.loc[[0, 1], 'email']

0    CoreyMShafer@gmail.com
1         JaneDoe@gmail.com
Name: email, dtype: str

In [24]:
df.loc[[0, 1], ['last', 'email']]

     last                   email
0  Shafer  CoreyMShafer@gmail.com
1     Doe       JaneDoe@gmail.com