In [1]:
import pandas as pd
import numpy as np

In [8]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [29]:
df = pd.DataFrame(people)

df.replace('NA', np.nan, inplace=True)
df.replace('Missing', np.nan, inplace=True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [10]:
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [11]:
# We are gonna have some missing data --> remove it
# Remove the rows that do have those (all) missing values
df.dropna() # .dropna() method is using some default arguments (check next code lines)

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [15]:
df.dropna(axis='index', how='any') # here, we show the default arguments for the .dropn() method has
# first argument: access argument
    # This can either be set to index or set to columns --> Tells Pandas that we are gonna drop na values when our rows are missing values (here set to default by 'index', if 'columns' provided then we would be dropping columns )
# second argument: Criteria used for dropping a row (or a column) (how we want to drop these)

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [17]:
# if we set our how to 'all', then we will drop only (in this case) the ROWS when all of the values in that row are msising
df.dropna(axis='index', how='all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [19]:
# if we set our how to 'all', then we will drop only (in this case) the COLUMNS when all of the values in that row are msising
df.dropna(axis='columns', how='all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [21]:
# Here, since we have at least one na value in each of our rows, then it will print an empty data frame
df.dropna(axis='columns', how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [24]:
# we can also pass a subset argument, in this case the column name 'email' that we are checking for missing values (NaN)
df.dropna(axis='index', how='any', subset=['email'])
# recall the 'NA' value is our custome missing values (check for the next lines of code)

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [25]:
# same print as before for the set value arg to 'all':
df.dropna(axis='index', how='all', subset=['email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [27]:
# Now here, in order for a row to be dropped, then both argument contents from our subset have to match (None or NaN)
df.dropna(axis='index', how='all', subset=['last', 'email'])
# remember that in order to permanently update our data frame with further changes, we need to specify the 'inplace=True' argument

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [31]:
# How can we handle custom missing values?
# --> Use the .replace() method (together when defining your df) so we can replace all the custom missing values with the numpy 'np.nan'
# after update are done:
df.dropna(axis='index', how='all', subset=['last', 'email'])

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
5    NaN      NaN      Anonymous@email.com  NaN

In [33]:
df.isna() # method .isna() classifies the values of our datafrase as whether if they are (True) or they ar not (Fase) a NA value

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [35]:
# We might want to fill our na values with a particulr value
# student --> assignment --> not delivered --> na --> 0's

df.fillna('0') # more useful for numerical data

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

In [37]:
# Let's say that we wanted to get the average age of all the people in our sample df
# Check what type of data do we have for our age column:
df.dtypes # use the .dtypes attribute
# we can see that the 'age' column stores dat aof type str

first    str
last     str
email    str
age      str
dtype: object

In [38]:
# recall that our 'np.nan' values have float type of data
type(np.nan)
# therefore, we would need to set those for floats

float

In [40]:
# Le'ts conver out 'email' column values into numbers:
# Next line of code doesn't work because there are some 'np.nan' values for the 'email' columns, and remember that those are of type float
df['age'] = (df['age'].astype(int))

ValueError: cannot convert float NaN to integer

In [43]:
# therefore, we need to instead set the column value change to float type
df['age'] = (df['age'].astype(float))

In [44]:
# now, we can successfuly get the average for the 'age' column values without caring about the missing values problems:
df['age'].mean()

np.float64(46.75)