In [1]:
import pandas as pd

In [2]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@gmail.com', 'JohnDoe@gmail.com']
}

In [3]:
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [4]:
# In this video we will be learning how to alter/update existing rows and columns' data in our dfs
# last videos --> filter data --> same concepts, ude them to make changes in uour data.

df.columns # .columns attribute to see all our columns' names

Index(['first', 'last', 'email'], dtype='str')

In [7]:
# first --> first name
# rename all of the columns --> do an assignment using the .columns attribute we just used

df.columns = ['first_name', 'last_name', 'email']
df.columns

Index(['first_name', 'last_name', 'email'], dtype='str')

In [8]:
# change something specific about each column in our dataframe
# e.g. your columns are all uppercase and we want them to be lowercase or viceversa
# In this case we can use a list comprehension 
df.columns = [x.upper() for x in df.columns]
df.columns

Index(['FIRST_NAME', 'LAST_NAME', 'EMAIL'], dtype='str')

In [9]:
# remove spaces and replace them with underscores
# using the . notation to access a column name --> does not work if there are spaces in the column names
df.columns = df.columns.str.replace(' ', "_") # using both .str(), referenced method, and .replace() method --> replace('...', '...') --> replace all first arguments for second arguments  
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [11]:
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [16]:
# What if we wanted to change only some columns?
df.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True) # .replace() method needs to update changes as definitive changes --> inplace=True 
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [19]:
# Let's update a value out of a row:
df.loc[2] = ['John', 'Smith', 'JohnSmith@gmail.com']
df.loc[[2]]

  first   last                email
2  John  Smith  JohnSmith@gmail.com

In [28]:
# What if had a lot of columns but we only wanted to change a couple of values?
# We can just specify the exact columns using .loc[...] --> when learnt it before when we use .loc[] to filter data.

df.loc[2, ['last', 'email']] = ['Doe', 'JohnDoe@gmail.com']
df.loc[[2]]

  first last              email
2  John  Doe  JohnDoe@gmail.com

In [29]:
# Change only one value (no necessity of passing a list)
df.loc[2, 'last'] = 'Smith'
df.loc[[2]]

  first   last              email
2  John  Smith  JohnDoe@gmail.com

In [30]:
# we have another indexer 'at, specifically meant for changing or looking up a single value
df.at[2, 'last'] = 'Doe'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [32]:
# mistake that is very common --> changing a value WITHOUT using any of this indexers
# How we update a single row of data
filt = (df['email'] == 'JohnDoe@gmail.com')
df.loc[filt, 'last'] = 'Smith'
df.loc[[2]]

  first   last              email
2  John  Smith  JohnDoe@gmail.com

In [36]:
# How do we update multiple row values of data
# multiple ways
# let's assume that we want to change all of the email addresses so that they are lowercase --> make email addresses easy to search to
# we can just assign that column to the lowercase value of itself
df['email'] = (df['email'].str.lower()) # use the str class on the Series obj (email column) and use the lower() method on that str class
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@gmail.com
2   John    Smith        johndoe@gmail.com

In [37]:
# several ways we can update multiple row values of data (very similar):
"""
apply
map
applymap
replace
"""

'\napply\nmap\napplymap\nreplace\n'

In [38]:
# apply: 
    # - used for calling a function on our values
    # - can work on either a data frame or a Series obj
    # - when we use this on a Series, it can apply a function to every value in our series

# Let's say we want to see the length of all our email addresses, maybe we have a website and want to make sure all of the email addresses are too long or something like that
df['email'].apply(len) # we get the length of each of our 'email' column Series obj values

0    23
1    17
2    17
Name: email, dtype: int64

In [45]:
# We can also use apply to update values
# we will create a simple function that returns the uppercase version of our email, 
# but the function can be as complicated as you want it to be.
def update_email(email):
    return email.upper()

# this doesn't change our values/rows, so we have to assign it to our column
df['email'] = (df['email'].apply(update_email)) # we can pass in the function we just wrote (we don't want to execute the function so we do not set its parenthesis when passing it in for our .apply() method)
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane      Doe        JANEDOE@GMAIL.COM
2   John    Smith        JOHNDOE@GMAIL.COM

In [48]:
# for easy functions as well, you might see people using lambda functions as well
# lambda functions --> anonymous functions (with a specific name or without a specific name) that we can use for things like this
# let's do one of this lambda functions for this example
# let's convert the 'email' column values back to lowercase:

df['email'] = (df['email'].apply(lambda x: x.lower())) # 'lambda x:' --> function with no name, ' x.upper()' --> function's body
df
# This is how apply works on Series objects

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@gmail.com
2   John    Smith        johndoe@gmail.com

In [50]:
# Now let's look at how apply works with data frames
# when we ran .apply() on a Series obj, it ran a function on all of the values in that Series obj
# Now, when we run .apply() on a dataframe, it runs a function on each row or column of that data frame 
df.apply(len) # referncing our dataframe rather than its Series obj; len as length function (no parenthesis) which is the argument for our .apply() method
# it applies the length function len() to each Series obj in the dataframe (specifically the columns)
# that is just the number of rows in each column

first    3
last     3
email    3
dtype: int64

In [51]:
# We can get that same result for a specific Series obj if we manually check the length of one of these
len(df['email'])

3

In [53]:
# we can also have this apply to columns as well if you change the axis:
df.apply(len, axis='columns') # 'rows' as default

0    3
1    3
2    3
dtype: int64

In [55]:
# Basically, we want to use functions that will make sense to be used on a Series obj when using ,apply() on an entire data frame
# e.g. let's say we wanted to grab the minimum value from each column 
# --> Series objs have a min method, so we could pass that into apply and see the minimum value for each Series
# sample dataframe --> all string values --> min value from a Series of strings --> return the first one in alph order

df.apply(pd.Series.min)
# numerical data returns the min numbers

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: str

In [58]:
# We could use lambda functions with this as well
# remember that lambda will be working on a Serries obj
df.apply(lambda x: x.min()) # x is going to be a Series, it's not going to be a value (Series have the min() method)

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: str

In [61]:
# Running apply() on a Series --> appplies a function to every value in the Series
# Running apply() on a data frame --> applies a function on every Series in the dataframe

# how we can apply a function to every individual element in the dataframe?
# --> That's where 'apply map' is useful; 'apply map' only works on dataframes, Series obj do not have the apply method
# OLD VERSION: ---> df.applymap(len)
# NEW VERSION:
df.map(len) # --> Applying the function len() to every individual element in our data frame

   first  last  email
0      5     7     23
1      4     3     17
2      4     5     17

In [62]:
# If we wanted all values in our data frame to be lowercase, then:
df.map(str.lower) # passing the .str.lower() method (rmember all our values in this dataframe are strings)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@gmail.com
2   john    smith        johndoe@gmail.com

In [64]:
# .map() is used fos substituting each value in a Series with another value.
# Let's say we want to substitute a couple of our first names:
df['first'].map({'Corey': 'Chris', 'Jane': 'Mary'}) # passing into .map() a dictionary with the values we want to substitute
# The values that we did not substituted are now converted into NaN values

0    Chris
1     Mary
2      NaN
Name: first, dtype: str

In [67]:
# What if we wanted to keep John but just substitute these other names?
# Instead of using .map() we can use the .replace() method

# REMEMBER THAT none of these codes represent a change in the original data, 
# so we have to:

df['first'] = (df['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'}))
df

   first     last                    email
0  Chris  Schafer  coreymschafer@gmail.com
1   Mary      Doe        janedoe@gmail.com
2   John    Smith        johndoe@gmail.com